---
- hosts: localhost    #jenkins server
  vars:
    state: present
    s3_bucket: javahome-tf-1209023
    key: terraform.tfstate
    region: ap-southeast-1
    app_env: dev
  tasks:
    - name: Run terraform scripts
      terraform:
        project_path: "./"
        state: "{{state}}"
        backend_config:
          bucket: "{{s3_bucket}}"
          key: "{{key}}"
          region: "{{region}}"
        variables_files: "{{app_env}}.tfvars"
        workspace: "{{app_env}}
